In [3]:
import camelot

# Read the PDF file
tables = camelot.read_pdf('C:\\Users\\abdel\\Desktop\\Implantation Bancaire 2023 VF.pdf', pages='9-end')

In [8]:
regions = ["Tangier-Tetouan-Al Hoceima",
           "L'Oriental",
           "Fez-Meknes",
           "Rabat-Salé-Kénitra",
           "Béni Mellal-Khénifra",
           "Casablanca-Settat",
           "Marrakech-Safi",
           "Drâa-Tafilalet",
           "Souss-Massa",
           "Guelmim-Oued Noun",
           "Laâyoune-Sakia El Hamra",
           "Dakhla-Oued Ed-Dahab"]

In [28]:
import pandas as pd
tables[0].df

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,,AL BARID BANK,ARAB BANK PLC,ATTIJARIWAFA \nBANK,BANCO SABADELL,BANK AL-AMAL,BANK OF AFRICA,BMCI,CAIXA BANK,CFG GROUP,...,UMB,BANK ASSAFA,UMNIA BANK,BANK AL YOUSR,AL AKHDAR BANK,BTI BANK,DAR AL-AMANE,NAJMAH,ARREDA,TOTAL
1,TANGER-TETOUAN-AL HOCEIMA \n80 \n0 \n101 \n0 \...,,,,,,,,,,...,,,,,,,,,,
2,AIN DORIJ,,,,,,,,,,...,,,,,,,,,,1
3,AJDIR,1,,1,,,,,,,...,,,,,,,,,,3
4,AL HOCEIMA,7,,5,,,3,1,,,...,1,,1,,,,,,,33
5,ASSILAH,1,,2,,,1,1,,,...,,,,,,,,,,9
6,BAB BERRED,1,,,,,,,,,...,,,,,,,,,,3
7,BAB TAZA,1,,,,,,,,,...,,,,,,,,,,2
8,BNI AHMED CHERQIA,1,,,,,,,,,...,,,,,,,,,,2
9,BNI AMMART,1,,,,,,,,,...,,,,,,,,,,2
10,BNI BOUAYACH,1,,1,,,,,,,...,,,,,,,,,,5
11,BNI BOUFRAH,1,,,,,,,,,...,,,,,,,,,,2
12,BNI GARFETT,1,,,,,,,,,...,,,,,,,,,,1
13,BNI HADIFA,1,,,,,,,,,...,,,,,,,,,,2
14,CHEFCHAOUEN,3,,1,,,1,1,,,...,,,,,,,,,,11
15,CHRAFAT,,,,,,,,,,...,,,,,,,,,,1
16,DAR BNI KARRICH,1,,,,,,,,,...,,,,,,,,,,1
17,DAR CHAOUI,1,,,,,,,,,...,,,,,,,,,,1
18,FNIDEQ,1,,2,,,2,,,,...,,,,,,,,,,12
19,GUEZNAIA,1,,,,,,,,,...,,,,,,,,,,1
20,HAD AL GHARBIA,1,,,,,,,,,...,,,,,,,,,,1
21,IMZOUREN,1,,3,,,1,,,,...,,,,,,,,,,9
22,ISSAGUEN,1,,1,,,,,,,...,,,,,,,,,,4
23,JEBHA,1,,1,,,,,,,...,,,,,,,,,,2
24,KSAR EL KEBIR,2,,4,,,2,1,,,...,,,,,,,,,,20
25,KSAR SGHIR,1,,1,,,,,,,...,,,,,,,,,,4
26,LAOUAMRA,1,,1,,,,,,,...,,,,,,,,,,4
27,LARACHE,3,,4,,,3,1,,,...,,,1,,,,,,,26
28,MALLOUSSA,1,,,,,,,,,...,,,,,,,,,,1
29,MARTIL,2,,2,,,2,1,,,...,,,,,,,,,,14
30,M'DIQ,2,,2,,,1,,,,...,,,,,,,,,,9
31,MOQRISSET,1,,,,,,,,,...,,,,,,,,,,1
32,OUED LAOU,1,,1,,,,,,,...,,,,,,,,,,4
33,OUEZZANE,2,,2,,,1,,,,...,,,,,,,,,,13
34,SAHEL,1,,,,,,,,,...,,,,,,,,,,2
35,SIDI BOUAFIF,,,,,,,,,,...,,,,,,,,,,1
36,SIDI BOUSBER,1,,,,,,,,,...,,,,,,,,,,1
37,SIDI LYAMANI,1,,,,,,,,,...,,,,,,,,,,1
38,SIDI REDOUANE,1,,,,,,,,,...,,,,,,,,,,1
39,TANGER,19,,50,,,33,15,1,1,...,1,2,2,1,1,,1,1,1,249
40,TARGUIST,1,,1,,,1,,,,...,,,,,,,,,,5
41,TATOFT,1,,,,,,,,,...,,,,,,,,,,1
42,TEROUAL,1,,,,,,,,,...,,,,,,,,,,1
43,TETOUAN,9,,16,,,13,3,,,...,1,1,1,1,1,,1,1,,81
44,ZOUMI,1,,,,,,,,,...,,,,,,,,,,2

In [29]:
# Step 3: Map cities to regions
result_dict = {}

for table,region in zip(tables,regions):
    df = table.df
    # Convert column 28 (index 28) to numeric, handling errors by coercing invalid values to NaN
    df.iloc[:, 28] = pd.to_numeric(df.iloc[:, 28], errors='coerce')
    # Step 2: Filter cities with more than 10 banks
    filtered_cities = df[df.iloc[:, 28] > 10]  # Column 28 is index 28 (0-based)
    filtered_cities = filtered_cities.iloc[:, 0].tolist()  # Column 1 is index 0 (0-based)
    result_dict[region]=filtered_cities

In [30]:
result_dict

{'Tangier-Tetouan-Al Hoceima': ['AL HOCEIMA',
  'CHEFCHAOUEN',
  'FNIDEQ',
  'KSAR EL KEBIR',
  'LARACHE',
  'MARTIL',
  'OUEZZANE',
  'TANGER',
  'TETOUAN'],
 "L'Oriental": ['AL AAROUI',
  'BERKANE',
  'GUERCIF',
  'NADOR',
  'OUJDA',
  'TAOURIRT'],
 'Fez-Meknes': ['AZROU',
  'EL HAJEB',
  'FES',
  'MEKNES',
  'SEFROU',
  'TAOUNATE',
  'TAZA'],
 'Rabat-Salé-Kénitra': ['KENITRA',
  'KHEMISSET',
  'RABAT',
  'SALE',
  'SIDI KACEM',
  'SIDI SLIMANE',
  'SKHIRATE',
  'TEMARA',
  'TIFLET'],
 'Béni Mellal-Khénifra': ['AZILAL',
  'BENI MELLAL',
  'FQUIH BEN SALAH',
  'KASBA TADLA',
  'KHENIFRA',
  'KHOURIBGA',
  'OUED ZEM',
  'SOUK SEBT OULED NEMMA'],
 'Casablanca-Settat': ['AZEMMOUR',
  'BENSLIMANE',
  'BERRECHID',
  'BOUSKOURA',
  'BOUZNIKA',
  'CASABLANCA',
  'DAR BOUAZZA',
  'EL JADIDA',
  'MOHAMMEDIA',
  'SETTAT',
  'SIDI BENNOUR',
  'TIT MELLIL'],
 'Marrakech-Safi': ['BEN GUERIR',
  'EL KELAA DES SRARHNA',
  'ESSAOUIRA',
  'MARRAKECH',
  'SAFI'],
 'Drâa-Tafilalet': [],
 'Souss-Massa': ['AGADIR',
  'AIT MELLOUL',
  'BIOUGRA',
  'DCHEIRA EL JIHADIA',
  'INEZGANE',
  'OULAD TEIMA',
  'TAROUDANNT',
  'TIZNIT'],
 'Guelmim-Oued Noun': ['GUELMIM', 'TAN TAN', 'LAAYOUNE']}

In [31]:
import json
# Step 1: Write the dictionary to a JSON file
output_file = './cities.json'  # Name of the output JSON file

with open(output_file, 'w') as json_file:
    json.dump(result_dict, json_file, indent=4)  # indent=4 for pretty formatting

print(f"Dictionary has been written to {output_file}")

Dictionary has been written to ./cities.json